import { test, expect } from '@playwright/test';
import { VISUAL_REGRESSION_EMPTY_USER, VISUAL_REGRESSION_POPULATED_USER } from './fixtures/visual-regression-users';

/**
 * Visual-regression baselines for the assembled dashboard
 * (`DASHBOARD_UI_SHARED_T-9`). Compares the app against **its own committed
 * baseline**, never against `resources/UI/portfolio-dashboard.html` — see
 * `specs/dashboard-ui/spec.md`'s Non-Goals for why a mockup diff would fail
 * by design. Scoped to one full-page screenshot each of the populated and
 * empty dashboard, at the config's single default desktop viewport — not
 * every component, not every breakpoint (see the task file).
 *
 * Baselines are platform-specific (font rasterisation/scrollbar metrics
 * differ macOS vs Linux) and MUST be generated/updated inside the
 * `mcr.microsoft.com/playwright:v*-jammy` container so local and CI
 * rasterise identically — see `apps/web/e2e/README.md` for the exact
 * command. A baseline generated natively on a laptop will fail on every CI
 * run with a diff no human can see.
 */

/**
 * Every screenshot renders with the browser's `Date` pinned here.
 *
 * The dashboard once held a date input defaulting to today's date (the
 * recommended-portfolios upload, since moved to `/data-sources`). A mask is
 * sized to its element, so a change in the date's rendered width leaked into
 * the screenshot at UTC day rollovers. That input is gone, but the clock stays
 * pinned so nothing wall-clock-derived can reintroduce the flake. The value is
 * the date the committed baselines were generated on; changing it means
 * regenerating them.
 */
const FIXED_NOW = new Date('2026-09-23T12:00:00Z');

async function login(page: import('@playwright/test').Page, user: { email: string; password: string }) {
  // Before the first navigation, so no page ever observes the real clock.
  await page.clock.setFixedTime(FIXED_NOW);
  await page.goto('/login');
  await page.getByLabel('Email').fill(user.email);
  // `exact` so the lookup doesn't also match the "Show password" toggle, and
  // the submit button is scoped to the <form> so it isn't confused with the
  // mode switcher's own "Sign in" button above it (AuthScreen, auth-ui).
  await page.getByLabel('Password', { exact: true }).fill(user.password);
  await page.locator('form').getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/$/);
}

test('populated dashboard matches its committed baseline', async ({ page }) => {
  await login(page, VISUAL_REGRESSION_POPULATED_USER);

  // Wait for the real thing, not a timeout (see the task's own warning).
  // `AdvisorPanel` renders its `report` state (via `AdvisorAnalysisResult`)
  // synchronously from `initialAnalysis` — no client fetch on mount — and
  // `PerformanceRange` renders its `initialData` the same way, so neither
  // needs its own loading-state wait; what both need is confirmation that
  // client hydration has actually completed and painted, which the
  // presence of these two elements (one per section, the chart's SVG path
  // and the advisor panel's result footer, the last two dynamic sections in
  // the page's layout order) proves.
  await expect(page.getByTestId('portfolio-line')).toBeVisible();
  await expect(page.getByTestId('advisor-analysis-footer')).toBeVisible();

  await expect(page).toHaveScreenshot('dashboard-populated.png', {
    fullPage: true,
    // The footer's "Generated by <model> · <date>" text is derived from a
    // fixed `createdAt` in the seed data (see
    // `./fixtures/visual-regression-seed.ts`), but it's still formatted
    // through `Intl.DateTimeFormat`'s `timeStyle: 'short'`, which renders
    // relative to the machine's local timezone — masked here as a second,
    // independent guard against that varying between the container this
    // baseline was generated in and whatever machine re-runs the check.
    mask: [page.getByTestId('advisor-analysis-footer')],
  });
});

test('empty-portfolio dashboard matches its committed baseline', async ({ page }) => {
  await login(page, VISUAL_REGRESSION_EMPTY_USER);

  // This user has zero seeded holdings/snapshots/analysis (see
  // `./fixtures/visual-regression-users.ts`) — "finished rendering the
  // empty state" here means each section's own empty-state markup is on
  // screen: the performance chart's empty placeholder (`GET
  // /portfolio/performance` still resolves `200` with an empty series for a
  // user with no snapshots, so `PerformanceRange` renders and reaches
  // `PerformanceChart`'s own `series.length === 0` branch) and the advisor
  // panel's idle "Generate Portfolio Analysis" button (no analysis to load,
  // `GET /advisor/analysis/latest` 404s, which `(dashboard)/page.tsx`
  // treats as the normal new-user case with no error notice).
  await expect(page.getByTestId('performance-chart-empty')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Generate Portfolio Analysis' })).toBeVisible();

  await expect(page).toHaveScreenshot('dashboard-empty.png', { fullPage: true });
});
