import { randomUUID } from 'node:crypto';
import type { Client } from 'pg';

/**
 * Deterministic seed data for `dashboard-visual.spec.ts`'s "populated
 * dashboard" screenshot (`VISUAL_REGRESSION_POPULATED_USER`, see
 * `./visual-regression-users.ts`). Written directly via a plain `pg` client
 * — the same tool `global-setup.ts` already uses for its fixture-user
 * teardown — rather than through the live API: `POST /portfolio/holdings`
 * would trigger `MarketDataService.findOrCreateAsset` -> `backfillHistory`,
 * which reaches out to the real, rate-limited, non-deterministic Yahoo
 * Finance endpoint. Direct DB writes are the only way to get fully pinned,
 * reproducible numbers for a committed screenshot baseline.
 *
 * `Asset`/`Holding`/`PortfolioValueSnapshot`/`BenchmarkSnapshot`/
 * `AdvisorAnalysis` rows all declare `id` with no DB-level default
 * (`@default(uuid(7))` is a Prisma **client-side** default, not a Postgres
 * `DEFAULT` — see the migration SQL) — every row below generates its own id
 * with `randomUUID()` rather than relying on the database to supply one.
 */

/** Real-looking B3 tickers not already used by `apps/api/test/fixtures` or other e2e specs (checked at authoring time), so this seed can never collide with another suite's rows within the same `db-test` run. */
const VISUAL_REGRESSION_ASSETS = [
  {
    ticker: 'TAEE11',
    name: 'Transmissão Aliança de Energia Elétrica S.A.',
    sector: 'Utilities',
    currentPrice: 38.52,
    currentChangePct: 0.64,
  },
  {
    ticker: 'BBSE3',
    name: 'BB Seguridade Participações S.A.',
    sector: 'Financials',
    currentPrice: 34.18,
    currentChangePct: -0.31,
  },
  {
    ticker: 'RADL3',
    name: 'Raia Drogasil S.A.',
    sector: 'Consumer Staples',
    currentPrice: 27.44,
    currentChangePct: 1.12,
  },
  {
    ticker: 'EGIE3',
    name: 'Engie Brasil Energia S.A.',
    sector: 'Utilities',
    currentPrice: 42.07,
    currentChangePct: 0.08,
  },
] as const;

/** `{ ticker, quantity, avgPrice }` — fixed so market value/gain-loss on the holdings grid never changes between runs. */
const VISUAL_REGRESSION_HOLDINGS = [
  { ticker: 'TAEE11', quantity: 150, avgPrice: 30.0 },
  { ticker: 'BBSE3', quantity: 200, avgPrice: 28.5 },
  { ticker: 'RADL3', quantity: 100, avgPrice: 25.0 },
  { ticker: 'EGIE3', quantity: 80, avgPrice: 38.0 },
] as const;

/**
 * How many days before "now" (seed time) each `PortfolioValueSnapshot`/
 * `BenchmarkSnapshot` row falls, descending. **Relative to "now", not a
 * fixed calendar date**: `GET /portfolio/performance?range=6M&...` (the
 * exact call `(dashboard)/page.tsx` makes, see its own source) filters
 * snapshots to `date >= today - 6 months` server-side, computed at request
 * time from the real clock — there is no clock-pinning hook in this
 * harness (the API is a real, separately-booted `nest start` process, not
 * something Playwright can inject a fake `Date` into). A fixed absolute
 * date would silently age out of the 6M window and start rendering an
 * empty chart a few months after this file is written. Anchoring to `now`
 * keeps the *values* (and therefore the rendered chart/metrics) fixed while
 * keeping the window it falls in always valid — nothing about the chart or
 * metrics displays an actual calendar date (see `PerformanceChart.tsx`), so
 * this doesn't reintroduce the non-determinism the task warns about.
 */
const DAYS_AGO = [77, 70, 63, 56, 49, 42, 35, 28, 21, 14, 7, 0];

/** Portfolio total value per `DAYS_AGO` index — ascending overall, with small realistic up/down noise rather than a straight line. */
const PORTFOLIO_VALUES = [
  15740, 16050, 15890, 16410, 16700, 16550, 17120, 17390, 17200, 17950, 18300, 18723.6,
];

/** Fixed `totalInvested` for every snapshot — the four holdings' cost basis never changes in this seed. */
const TOTAL_INVESTED = 15740;

/** IBOVESPA index points per `DAYS_AGO` index, covering the same window so `benchmarkSeries`/`vsBenchmarkPct` come back real and non-empty. */
const BENCHMARK_VALUES = [
  126000, 126500, 125800, 127200, 127900, 127500, 128600, 129100, 128800, 130200, 130900, 131500,
];

/** A fixed past instant — never `now()` — so the advisor panel's "Generated by ... <date>" footer is pinned. Masked in the spec regardless (belt and suspenders, see `dashboard-visual.spec.ts`). */
const ADVISOR_ANALYSIS_CREATED_AT = new Date('2026-08-01T12:00:00.000Z');

function daysAgo(days: number): Date {
  const date = new Date();
  date.setUTCHours(0, 0, 0, 0);
  date.setUTCDate(date.getUTCDate() - days);
  return date;
}

/**
 * Deletes any pre-existing rows this seed itself owns, keyed by the fixed
 * tickers/user emails above — safe to run unconditionally before every
 * suite run (idempotent, same rationale as `global-setup.ts`'s
 * `FIXTURE_USER` teardown). Deletes in FK order: holdings/snapshots/
 * analyses before the users and assets they reference.
 */
export async function cleanupVisualRegressionFixtures(
  client: Client,
  emails: string[],
): Promise<void> {
  const { rows } = await client.query<{ id: string }>(
    'SELECT id FROM users WHERE email = ANY($1)',
    [emails],
  );
  const userIds = rows.map((row) => row.id);

  if (userIds.length > 0) {
    await client.query('DELETE FROM advisor_analyses WHERE user_id = ANY($1)', [userIds]);
    await client.query('DELETE FROM advisor_reports WHERE user_id = ANY($1)', [userIds]);
    await client.query('DELETE FROM portfolio_value_snapshots WHERE user_id = ANY($1)', [
      userIds,
    ]);
    await client.query('DELETE FROM holdings WHERE user_id = ANY($1)', [userIds]);
    await client.query('DELETE FROM recommended_portfolios WHERE user_id = ANY($1)', [userIds]);
    await client.query('DELETE FROM users WHERE id = ANY($1)', [userIds]);
  }

  // Assets are ticker-unique and exclusively owned by this fixture (see the
  // "not already used" note above), so they're safe to drop unconditionally
  // by ticker rather than needing a user-scoped lookup first.
  const tickers = VISUAL_REGRESSION_ASSETS.map((asset) => asset.ticker);
  await client.query('DELETE FROM assets WHERE ticker = ANY($1)', [tickers]);

  // `BenchmarkSnapshot` isn't user-scoped, so a re-run on the same calendar
  // day (same `DAYS_AGO` -> same dates) would otherwise hit its
  // `(benchmark, date)` unique constraint — cleared here for idempotency.
  // Re-runs on a *different* day naturally leave the previous day's rows
  // behind (there's no user/fixture marker on this table to scope a
  // broader delete by); harmless in `db-test`, which CI recreates from
  // scratch every run.
  const seededDates = DAYS_AGO.map((days) => daysAgo(days));
  await client.query(
    "DELETE FROM benchmark_snapshots WHERE benchmark = 'IBOVESPA' AND date = ANY($1)",
    [seededDates],
  );
}

/**
 * Seeds `VISUAL_REGRESSION_POPULATED_USER`'s "populated dashboard" state:
 * 4 assets, 4 matching holdings, a 12-point portfolio value series with a
 * matching IBOVESPA benchmark series over the same window, and one
 * `AdvisorAnalysis` with non-empty strengths/risks/recommendations/impact
 * metrics (this is the "populated" screenshot — it should exercise the
 * non-empty-column rendering, not the empty-state one).
 */
export async function seedVisualRegressionPopulatedUser(
  client: Client,
  userId: string,
): Promise<void> {
  const assetIdByTicker = new Map<string, string>();

  for (const asset of VISUAL_REGRESSION_ASSETS) {
    const id = randomUUID();
    assetIdByTicker.set(asset.ticker, id);
    await client.query(
      `INSERT INTO assets (id, ticker, name, sector, current_price, current_change_pct, price_updated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [id, asset.ticker, asset.name, asset.sector, asset.currentPrice, asset.currentChangePct, new Date()],
    );
  }

  for (const holding of VISUAL_REGRESSION_HOLDINGS) {
    const assetId = assetIdByTicker.get(holding.ticker);
    if (!assetId) {
      throw new Error(
        `visual-regression seed: no asset seeded for ticker ${holding.ticker} — VISUAL_REGRESSION_HOLDINGS and VISUAL_REGRESSION_ASSETS have drifted apart.`,
      );
    }
    const now = new Date();
    await client.query(
      `INSERT INTO holdings (id, user_id, asset_id, quantity, avg_price, created_at, updated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [randomUUID(), userId, assetId, holding.quantity, holding.avgPrice, now, now],
    );
  }

  for (let index = 0; index < DAYS_AGO.length; index += 1) {
    const date = daysAgo(DAYS_AGO[index]);
    await client.query(
      `INSERT INTO portfolio_value_snapshots (id, user_id, date, total_value, total_invested)
       VALUES ($1, $2, $3, $4, $5)`,
      [randomUUID(), userId, date, PORTFOLIO_VALUES[index], TOTAL_INVESTED],
    );
    await client.query(
      `INSERT INTO benchmark_snapshots (id, benchmark, date, value)
       VALUES ($1, 'IBOVESPA', $2, $3)
       ON CONFLICT (benchmark, date) DO NOTHING`,
      [randomUUID(), date, BENCHMARK_VALUES[index]],
    );
  }

  await client.query(
    `INSERT INTO advisor_analyses (
       id, user_id, advisor_report_id, recommended_portfolio_ids,
       score, summary, strengths, risks, recommendations, impact_metrics,
       model, created_at
     ) VALUES ($1, $2, NULL, $3::jsonb, $4, $5, $6::jsonb, $7::jsonb, $8::jsonb, $9::jsonb, $10, $11)`,
    [
      randomUUID(),
      userId,
      JSON.stringify([]),
      7.5,
      'This portfolio shows solid diversification across utilities, financial, and consumer staples sectors, with a tilt toward defensive, dividend-paying names. Overall risk is moderate and the recent uptrend outpaces the Ibovespa benchmark.',
      JSON.stringify([
        'Diversified across 4 sectors with no single holding above 40% of portfolio value.',
        'Heavy weighting toward dividend-paying utilities and financials, which have historically shown lower volatility.',
        'Consistent price appreciation across all four holdings over the trailing period.',
      ]),
      JSON.stringify([
        'Concentration in rate-sensitive utilities and financials leaves the portfolio exposed to a rising-rate environment.',
        'No exposure to small caps or growth sectors, limiting upside in a risk-on market.',
        'Zero fixed-income or cash allocation to cushion a broad equity drawdown.',
      ]),
      JSON.stringify([
        'Consider adding a small-cap or growth allocation to diversify return drivers.',
        'Introduce a fixed-income sleeve to reduce overall portfolio volatility.',
        'Monitor BBSE3 and EGIE3 position sizes, which together make up over half the portfolio.',
      ]),
      JSON.stringify([
        { label: 'Diversification Score', value: '7.2/10' },
        { label: 'Est. Volatility Reduction', value: '-1.8%' },
        { label: 'Projected Yield', value: '+0.6%' },
      ]),
      'claude-sonnet-5',
      ADVISOR_ANALYSIS_CREATED_AT,
    ],
  );
}
